name: Demo CLI Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  demo-cli:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install libomp (macOS only)
        if: runner.os == 'macOS'
        run: |
          brew install libomp

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run omg.py demo CLI
        run: |
          python omg.py --show-stats --show-timing --output matches.json demo/demo.omg demo/CIA_Briefings_of_Presidential_Candidates_1952-1992.txt
          if [ -f matches.json ]; then head -n 10 matches.json; fi
        shell: bash

      - name: Run highlighter.py demo CLI
        run: |
          python highlighter.py demo/CIA_Briefings_of_Presidential_Candidates_1952-1992.txt matches.json CIA_demo.html
          if [ -f CIA_demo.html ]; then head -n 10 CIA_demo.html; fi
        shell: bash
